[build]
builder = "NIXPACKS"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 2
healthcheckTimeout = 300
startCommand = "uvicorn app_1:app --host 0.0.0.0 --port $PORT"