[build]​
builder = "NIXPACKS"

[deploy]​
numReplicas = 1​
healthcheckPath = "/health"​
healthcheckTimeout = 300​
sleepApplication = false​
restartPolicyType = "ON_FAILURE"​
restartPolicyMaxRetries = 2
startCommand = "uvicorn app_1:app --host 0.0.0.0 --port $PORT"​